heat_template_version: 2013-05-23

description: |
  A [Minecraft Multiplayer Server](http://minecraft.gamepedia.com/Setting_up_a_server)
  running on a single Linux Cloud Server. The default version is
  1.8 unless otherwise specified.

parameter_groups:

- label: Server Settings
  parameters:
  - image
  - flavor

- label: Minecraft Settings
  parameters:
  - terms
  - minecraft_server_port
  - minecraft_gamemode
  - minecraft_spawn_animals
  - minecraft_spawn_npcs
  - minecraft_spawn_monsters

- label: rax-dev-params
  parameters:
  - server_hostname
  - kitchen
  - chef_version
  - minecraft_version

parameters:

  server_hostname:
    label: Server Name
    description: Hostname to use for setting the server name.
    type: string
    default: minecraft
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PV)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PV)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 4 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  terms:
    label: Agree to Terms
    description: |
      Required: You must agree to the Minecraft EULA found here:
      https://account.mojang.com/documents/minecraft_eula
    type: boolean
    constraints:
    - allowed_values:
      - true
      description: Terms must be accepted.

  minecraft_server_port:
    label: Minecraft Server Port
    description: Port to run Minecraft server on
    type: number
    default: 25565
    constraints:
    - range:
        min: 1024
        max: 65535
      description: |
        Port must be an unprivileged port in the range of 1024-65535

  minecraft_gamemode:
    label: Game Mode
    description: Mode of gameplay
    type: number
    default: 0
    constraints:
    - range:
        min: 0
        max: 3
      description: |
        0: Survival, 1: Creative, 2: Adventure, 3: Spectator

  minecraft_spawn_animals:
    label: Spawn Animals
    description: Spawn animals
    type: string
    default: "true"
    constraints:
    - allowed_values:
      - "true"
      - "false"

  minecraft_spawn_npcs:
    label: Spawn Villagers
    description: Spawn villagers
    type: string
    default: "true"
    constraints:
    - allowed_values:
      - "true"
      - "false"

  minecraft_spawn_monsters:
    label: Spawn Monsters
    description: Spawn monsters
    type: string
    default: "true"
    constraints:
    - allowed_values:
      - "true"
      - "false"

  minecraft_version:
    label: Minecraft Version
    description: Version of minecraft to install
    type: string
    default: 1.8

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/minecraft

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.16.0

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  minecraft_server:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

  minecraft_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: minecraft_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [minecraft_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        minecraft:
          url:
            str_replace:
              template: https://s3.amazonaws.com/Minecraft.Download/versions/%minecraft_version%/minecraft_server.%minecraft_version%.jar
              params:
                "%minecraft_version%": { get_param: minecraft_version}
          checksum: 40e23f3823d6f0e3cbadc491cedb55b8ba53f8ab516b68182ddd1536babeb291
          accept_eula: { get_param: terms }
          properties:
            server-port: { get_param: minecraft_server_port }
            query.port: { get_param: minecraft_server_port }
            rcon.port: 25575
            gamemode: { get_param: minecraft_gamemode }
            spawn-animals: { get_param: minecraft_spawn_animals }
            spawn-npcs: { get_param: minecraft_spawn_npcs }
            spawn-monsters: { get_param: minecraft_spawn_monsters }
        rax:
          firewall:
            tcp: [ { get_param: minecraft_server_port } ]
        run_list: ["recipe[apt]",
                   "recipe[java::openjdk]",
                   "recipe[minecraft]",
                   "recipe[rax-firewall]"]


outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    description: Server IP
    value: { get_attr: [minecraft_server, accessIPv4] }

  server_port:
    description: Minecraft Port
    value: { get_param: minecraft_server_port }
